#!/bin/bash
# Build UTUVO Orbit and bundle a runnable .app for local testing.
# ad-hoc signed, no Gatekeeper modifications, no remote upload.

set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG="${CONFIG:-release}"
APP_NAME="UTUVO Orbit"
BUNDLE_ID="com.utuvo.orbit"
EXECUTABLE="UtuvoOrbit"
APP="$PWD/dist/$APP_NAME.app"
VERSION="0.4.1"
BUILD_NUMBER="7"

echo "==> Building $EXECUTABLE ($CONFIG)…"
swift build -c "$CONFIG"

echo "==> Assembling $APP_NAME.app…"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp ".build/$CONFIG/$EXECUTABLE" "$APP/Contents/MacOS/$EXECUTABLE"
chmod +x "$APP/Contents/MacOS/$EXECUTABLE"
cp "Resources/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
# SwiftPM localized resources are needed by both the CLI and the packaged app.
cp -R ".build/$CONFIG/UtuvoOrbit_OrbitCore.bundle" "$APP/Contents/Resources/"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>CFBundleExecutable</key><string>$EXECUTABLE</string>
<key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
<key>CFBundleName</key><string>$APP_NAME</string>
<key>CFBundleDisplayName</key><string>$APP_NAME</string>
<key>CFBundlePackageType</key><string>APPL</string>
<key>CFBundleIconFile</key><string>AppIcon</string>
<key>CFBundleShortVersionString</key><string>$VERSION</string>
<key>CFBundleVersion</key><string>$BUILD_NUMBER</string>
<key>CFBundleDevelopmentRegion</key><string>en</string>
<key>CFBundleLocalizations</key><array><string>en</string><string>zh-Hant</string></array>
<key>LSMinimumSystemVersion</key><string>14.0</string>
<key>LSUIElement</key><true/>
<key>NSHighResolutionCapable</key><true/>
<key>NSHumanReadableCopyright</key><string>© 2026 UTUVO</string>
<key>NSSupportsAutomaticTermination</key><true/>
<key>NSSupportsSuddenTermination</key><false/>
</dict></plist>
PLIST

# App icon is original vector artwork, generated by scripts/render-brand.swift.

echo "==> Ad-hoc signing…"
codesign --force --sign - "$APP"
codesign --verify --strict --verbose=2 "$APP"
plutil -lint "$APP/Contents/Info.plist"

printf '\nBuild complete: %s\n' "$APP"
printf '\nTry:\n  open "%s"\n  .build/%s/%s --diagnose\n  .build/%s/%s --gallery\n  .build/%s/%s --fixture laptop\n' \
  "$APP" "$CONFIG" "$EXECUTABLE" "$CONFIG" "$EXECUTABLE" "$CONFIG" "$EXECUTABLE"
